; SECTION "Pics 1", ROMX ; BANK $09

IF GEN_2_GRAPHICS
MoltresPicFront:    INCBIN "gfx/pokemon/gsfront/moltres.pic"
MoltresPicBack:     INCBIN "gfx/pokemon/gsback/moltresb.pic"

TentacoolPicFront:  INCBIN "gfx/pokemon/gsfront/tentacool.pic"
TentacoolPicBack:   INCBIN "gfx/pokemon/gsback/tentacoolb.pic"
ScytherPicFront:    INCBIN "gfx/pokemon/gsfront/scyther.pic"
ScytherPicBack:     INCBIN "gfx/pokemon/gsback/scytherb.pic"
StaryuPicFront:     INCBIN "gfx/pokemon/gsfront/staryu.pic"
StaryuPicBack:      INCBIN "gfx/pokemon/gsback/staryub.pic"
BlastoisePicFront:  INCBIN "gfx/pokemon/gsfront/blastoise.pic"
BlastoisePicBack:   INCBIN "gfx/pokemon/gsback/blastoiseb.pic"
PinsirPicFront:     INCBIN "gfx/pokemon/gsfront/pinsir.pic"
PinsirPicBack:      INCBIN "gfx/pokemon/gsback/pinsirb.pic"
TangelaPicFront:    INCBIN "gfx/pokemon/gsfront/tangela.pic"
TangelaPicBack:     INCBIN "gfx/pokemon/gsback/tangelab.pic"

JolteonPicFront:    INCBIN "gfx/pokemon/gsfront/jolteon.pic"
JolteonPicBack:     INCBIN "gfx/pokemon/gsback/jolteonb.pic"
VaporeonPicFront:   INCBIN "gfx/pokemon/gsfront/vaporeon.pic"
VaporeonPicBack:    INCBIN "gfx/pokemon/gsback/vaporeonb.pic"
MachopPicFront:     INCBIN "gfx/pokemon/gsfront/machop.pic"
MachopPicBack:      INCBIN "gfx/pokemon/gsback/machopb.pic"
ZubatPicFront:      INCBIN "gfx/pokemon/gsfront/zubat.pic"
ZubatPicBack:       INCBIN "gfx/pokemon/gsback/zubatb.pic"
EkansPicFront:      INCBIN "gfx/pokemon/gsfront/ekans.pic"
EkansPicBack:       INCBIN "gfx/pokemon/gsback/ekansb.pic"
ParasPicFront:      INCBIN "gfx/pokemon/gsfront/paras.pic"
ParasPicBack:       INCBIN "gfx/pokemon/gsback/parasb.pic"
PoliwhirlPicFront:  INCBIN "gfx/pokemon/gsfront/poliwhirl.pic"
PoliwhirlPicBack:   INCBIN "gfx/pokemon/gsback/poliwhirlb.pic"
PoliwrathPicFront:  INCBIN "gfx/pokemon/gsfront/poliwrath.pic"
PoliwrathPicBack:   INCBIN "gfx/pokemon/gsback/poliwrathb.pic"
WeedlePicFront:     INCBIN "gfx/pokemon/gsfront/weedle.pic"
WeedlePicBack:      INCBIN "gfx/pokemon/gsback/weedleb.pic"
KakunaPicFront:     INCBIN "gfx/pokemon/gsfront/kakuna.pic"
KakunaPicBack:      INCBIN "gfx/pokemon/gsback/kakunab.pic"
BeedrillPicFront:   INCBIN "gfx/pokemon/gsfront/beedrill.pic"
BeedrillPicBack:    INCBIN "gfx/pokemon/gsback/beedrillb.pic"
ENDC

IF !GEN_2_GRAPHICS
MoltresPicFront:    INCBIN "gfx/pokemon/front/moltres.pic"
MoltresPicBack:     INCBIN "gfx/pokemon/back/moltresb.pic"

TentacoolPicFront:  INCBIN "gfx/pokemon/front/tentacool.pic"
TentacoolPicBack:   INCBIN "gfx/pokemon/back/tentacoolb.pic"
ScytherPicFront:    INCBIN "gfx/pokemon/front/scyther.pic"
ScytherPicBack:     INCBIN "gfx/pokemon/back/scytherb.pic"
StaryuPicFront:     INCBIN "gfx/pokemon/front/staryu.pic"
StaryuPicBack:      INCBIN "gfx/pokemon/back/staryub.pic"
BlastoisePicFront:  INCBIN "gfx/pokemon/front/blastoise.pic"
BlastoisePicBack:   INCBIN "gfx/pokemon/back/blastoiseb.pic"
PinsirPicFront:     INCBIN "gfx/pokemon/front/pinsir.pic"
PinsirPicBack:      INCBIN "gfx/pokemon/back/pinsirb.pic"
TangelaPicFront:    INCBIN "gfx/pokemon/front/tangela.pic"
TangelaPicBack:     INCBIN "gfx/pokemon/back/tangelab.pic"

JolteonPicFront:    INCBIN "gfx/pokemon/front/jolteon.pic"
JolteonPicBack:     INCBIN "gfx/pokemon/back/jolteonb.pic"
VaporeonPicFront:   INCBIN "gfx/pokemon/front/vaporeon.pic"
VaporeonPicBack:    INCBIN "gfx/pokemon/back/vaporeonb.pic"
MachopPicFront:     INCBIN "gfx/pokemon/front/machop.pic"
MachopPicBack:      INCBIN "gfx/pokemon/back/machopb.pic"
ZubatPicFront:      INCBIN "gfx/pokemon/front/zubat.pic"
ZubatPicBack:       INCBIN "gfx/pokemon/back/zubatb.pic"
EkansPicFront:      INCBIN "gfx/pokemon/front/ekans.pic"
EkansPicBack:       INCBIN "gfx/pokemon/back/ekansb.pic"
ParasPicFront:      INCBIN "gfx/pokemon/front/paras.pic"
ParasPicBack:       INCBIN "gfx/pokemon/back/parasb.pic"
PoliwhirlPicFront:  INCBIN "gfx/pokemon/front/poliwhirl.pic"
PoliwhirlPicBack:   INCBIN "gfx/pokemon/back/poliwhirlb.pic"
PoliwrathPicFront:  INCBIN "gfx/pokemon/front/poliwrath.pic"
PoliwrathPicBack:   INCBIN "gfx/pokemon/back/poliwrathb.pic"
WeedlePicFront:     INCBIN "gfx/pokemon/front/weedle.pic"
WeedlePicBack:      INCBIN "gfx/pokemon/back/weedleb.pic"
KakunaPicFront:     INCBIN "gfx/pokemon/front/kakuna.pic"
KakunaPicBack:      INCBIN "gfx/pokemon/back/kakunab.pic"
BeedrillPicFront:   INCBIN "gfx/pokemon/front/beedrill.pic"
BeedrillPicBack:    INCBIN "gfx/pokemon/back/beedrillb.pic"
ENDC